fix: stack overflow
jenkins-infra/pipeline-library pull request #335
Opened 2022-03-25 08:41 UTC by smerle33

correct a parameter for the unit test to go through when checkout from a branch.

2022-03-25 10:06 UTC, lemeurherve approved these changes

2022-03-25 10:44 UTC, timja commented on vars/infra.groovy
> +        checkout repo
`checkout scm` is the way of doing this, have you got a link for `checkout repo` I've never heard of it

2022-03-25 13:11 UTC, dduportal requested changes
+ 1 with Tim remark.

2022-03-25 13:11 UTC, dduportal commented on vars/infra.groovy
> +        checkout repo
```suggestion
        checkout scm
```

2022-03-25 15:00 UTC, smerle33 commented
@timja what do you think of removing the checkout method that is generating the stackoverflow from within the unit test ? I think that it should not have the same name as "checkout" ....

2022-03-29 07:36 UTC, dduportal commented on test/groovy/InfraStepTests.groovy
> +  //@Ignore("Some stackoverflow issues")
```suggestion
```

2022-03-29 07:37 UTC, timja commented
> @timja what do you think of removing the checkout method that is generating the stackoverflow from within the unit test ? I think that it should not have the same name as "checkout" ....

I think okay, seems to just be a legacy method delegating to checkoutSCM

2022-03-29 07:39 UTC, dduportal approved these changes

2022-03-29 07:40 UTC, timja approved these changes

2022-03-29 07:42 UTC, merged